import requests
import os

def create_github_issue():
    # 1. Retrieve the token from environment variables for security
    github_token = os.getenv("GITHUB_TOKEN")
    
    # 2. Configure your specific repository details
    # Replace these placeholders with your actual GitHub info
    username = "JuaRezZ17"
    repo_name = "devops-lab"
    
    if not github_token:
        print("Error: GITHUB_TOKEN environment variable is not set.")
        return

    # 3. Define the API endpoint and headers
    url = f"https://api.github.com/repos/{username}/{repo_name}/issues"
    
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    # 4. Define the Issue payload (JSON body)
    issue_data = {
        "title": "Weekly automation task",
        "body": "This issue was automatically generated by a Python DevOps script.",
        "assignees": [username],
        "labels": ["automation", "task"]
    }

    # 5. Execute the POST request
    print(f"Connecting to GitHub API to create an issue in {username}/{repo_name}...")
    response = requests.post(url, headers=headers, json=issue_data)

    # 6. Evaluate the response (201 means 'Created')
    if response.status_code == 201:
        issue_url = response.json().get('html_url')
        print("Success! Issue created successfully.")
        print(f"Issue Link: {issue_url}")
    else:
        print(f"Failed to create issue. Status Code: {response.status_code}")
        print(f"Response: {response.text}")

if __name__ == "__main__":
    create_github_issue()